### ISSUE TITLE
Generic Client jumps to the first example request after click SEND

### ISSUE THREAD

**Issue by bierett** [deegree/deegree3#374] opened 2014-08-08 14:29 UTC
### Actual Behaviour

If I select an example request from the list and click on the button `send`, the [Generic Client](http://localhost:8080/console/client/index.xhtml) jumps up to the first example request, but the selected file is shown in the drop down list.
### Expected Behaviour

If I execute an example request, the Generic Client shows the selected example request in the list and box.

**Comment by julianzz98** [comment] 2022-09-26 11:17
The bug is not reproducible in the version 3.5.0-SNAPSHOT (current main build) of deegree since the Generic OGC Web Service Client was removed, see https://github.com/deegree/deegree3/issues/1061 for more information.

**Comment by julianzz98** [comment] 2023-11-30 15:41
As of deegree version 3.5.0 the functionality to send requests via the console (button 'send requests') was removed. Therefore I am closing this issue.

**Closed by julianzz98** 2023-11-30 15:41 UTC
Labels: bug, console
