### ISSUE TITLE
Initialization of resource '*' failed

### ISSUE THREAD

**Issue by JoKord** [deegree/deegree3#1064] opened 2020-05-12 16:29 UTC
Hello.

Im am using Deegree3 version 3.4.11 and today for a reason I cannot explain all my SQLFeatureStores started are giving the following error:

Initialization of resource 'Appurtenance_Avenca' failed: Unable to build resource FeatureStoreProvider:Appurtenance_Avenca: Error building GML application schema: Severe error in schema document (systemId: null, line: -1, column: -1) Premature end of file.

I haven't changed anything in my FeatureStores and yesterday was working fine.
Is anyone else experiencing the same issues? 
It might be a broken link problem. 

Kind Regards,

**Comment by lgoltz** [comment] 2020-05-13 05:21
We also had some troubles tonight. It seems that some external schema files were not available.

**Comment by JoKord** [comment] 2020-05-13 08:53
Might it be related with Deegree3 external schema files or INSPIRE directive external schema files?

**Comment by ettweina** [comment] 2020-05-13 09:23
We have the same problems with SQLFeatureStores but on top with the LayerStoreProvider.
[10:19:58] ERROR: [DefaultWorkspace] Unable to build resource LayerStoreProvider:ps_fgeo_waldschutz: Dependent resource FeatureStoreProvider:ps_fgeo_waldschutz failed to initialize.
So I'am not really sure that the error comes from the schema.
We tested an SQLFeatureStore where we host the INSPIRESchemaFiles locally. Same error.

**Comment by mattenp** [comment] 2020-05-13 11:02
Yes, I have the same problem...
A workaround is to use all schema imports in xml-schema offline, also gml and gmd-schema
then you habe to change the schemaLocation in your INSPIRE-appschema

f. e. ElevationVectorElements.xsd
` <import namespace="http://inspire.ec.europa.eu/schemas/base/3.3" schemaLocation="BaseTypes.xsd"/>
  <import namespace="http://inspire.ec.europa.eu/schemas/el-bas/4.0" schemaLocation="ElevationBaseTypes.xsd"/>
  <import namespace="http://inspire.ec.europa.eu/schemas/gn/4.0" schemaLocation="GeographicalNames.xsd"/>
  <import namespace="http://inspire.ec.europa.eu/schemas/hy-p/4.0" schemaLocation="HydroPhysicalWaters.xsd"/>
<import namespace="http://www.isotc211.org/2005/gmd" schemaLocation="../gmd/gmd.xsd"/>
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="../gml/gml.xsd"/>`

I download schema-files this way:

`# gml 3.2.1
schema=http://schemas.opengis.net/gml/3.2.1/
schema_directory=gml
wget --no-check-certificate -e use_proxy=yes -e https_proxy=proxyhost:proxyPort $schema
egrep -o "href=\"[\%0-9a-zA-Z_-.()]*xml|href=\"[\%0-9a-zA-Z_-.()]*xsd" index.html | sed 's/href=\"//' > files.txt

for i in `cat files.txt`; do wget --no-check-certificate -e use_proxy=yes -e https_proxy=proxyhost:proxyPort "$schema/$i" -P ./inspire_offline/$schema_directory; done
rm index.html files.txt`

**Comment by JoKord** [comment] 2020-05-13 16:11
Is there no other way to solve the problem without having an offline xml-schema? 
And by the way if that is the problem then how can I download if the links for the schema are wrong and not working for deegree?
I guess I'm not fully understanding the problem here.

**Comment by stempler** [comment] 2020-05-13 18:58
If the problem is related to INSPIRE schemas the issue could be that they are now no longer available directly via `http://`, there now is a redirect to `https://`. If that's the issue here, then whatever is loading the schema can't handle the redirect. Even changing the schema URL to use https may not help, as some INSPIRE schemas reference other INSPIRE schemas in the schema files, using the http address.

**Comment by ettweina** [comment] 2020-05-14 06:19
Yes, that's exactly the problem.
If we change the URLs for the INSPIRE schemas (only possible in INSPIRE schemas which has no mor schemas included or to import) from http to https deegree can receive the schemas and the services can be build.
deegree cannot handle the automatic redirection to HTTPS of the INSPIRE reverse proxy. 
I've found this on the INSPIRE homepage. There is only mentioned the registry, but I suppose that the schemas are affected as well.
'In order to comply with the rules provided by our ICT Governance, we need to force the HTTPS protocol on the central INSPIRE registry service from 31 March. This means that all HTTP requests will be automatically redirected to HTTPS. The reference to items in the registry will still be implemented using HTTP URIs. Our reverse proxy will take care of the automatic redirection to HTTPS. If you have tools or applications accessing the registry, please make sure that they are capable of handling such redirects correctly.'

**Comment by ettweina** [comment] 2020-05-14 09:21
Alexander Dömming from GDI-DE made the following proposal:
XML-catalog (https://en.wikipedia.org/wiki/XML_catalog)
The XML catalog is a document describing a mapping between external entity references and locally cached equivalents. But perhaps it can also be used to map the http INSPIRE Urls to https URLs until deegree ist able to manage the redirect.
Is it possible to use XML-Catalog with deegree?
And if yes, how can I implement it?

**Comment by tfr42** [comment] 2020-05-15 09:13
@ettweina I am not aware if the XML-Catalog applies for XSD schema files too. The class responsible for resolving external files is https://github.com/deegree/deegree3/blob/51cdd20dd335715e045c89dd351b668e112edec2/deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/schema/RedirectingEntityResolver.java#L83

The implementation is using the Apache Xerxes 2.12.0 API.

This may be a good starting point to apply a patch.

The TMC will discuss this issue in the next TMC meeting, scheduled for Friday 2020-05-22.

**Comment by mattenp** [comment] 2020-05-15 10:12
Mail to JRC:

> since yesterday we can no longer use the INSPIRE application schemes online. I suppose it has to do with the HTTPS switchover (see https://github.com/deegree/deegree3/issues/1064 <https://urldefense.com/v3/__https://github.com/deegree/deegree3/issues/1064__;!!DOxrgLBm!XmZsEjW0bhDCmb9IeetrAk8BhVzm612qT046tEE9rGtJOOHmYVbnudiFtppZ_tgJDbqd15AS1WgyJA$>   and https://inspire.ec.europa.eu/news/inspire-re3gistry-software-and-inspire-registry-service-update <https://inspire.ec.europa.eu/news/inspire-re3gistry-software-and-inspire-registry-service-update>   ). 

answer from JRC-INSPIRE-SUPPORT@ec.europa.eu

> We have now restored the access to the schemas through http. Sorry for the inconvenience.

**Comment by tfr42** [comment] 2020-05-22 09:40
The TMC members conclude that the issue reported was caused by a change of the server setup providing the INSPIRE schema files. Nevertheless deegree shall support a properly configured server-sided redirect and retrieve external resources using HTTPS. This needs to be tested. To extend deegree to use bundled local files instead of remote resources we have created a new issue #1066. 
The TMC kindly asks JRC to keep us in the loop when changes of this magnitude are planned in the future.

**Comment by tfr42** [comment] 2021-02-03 09:54
Switch to HTTPS is planned for March 2021, see https://wiki.gdi-de.org/display/insp/2021/02/01/INSPIRE-Schemata+werden+von+HTTP+nach+HTTPS+migriert (German only)

**Comment by tfr42** [comment] 2021-03-02 15:54
Users have reported issues starting and reloading deegree workspace with references to INSPIRE schema files after 1st of March.

**Comment by tfr42** [comment] 2021-03-12 09:55
A temporary workaround is to use https instead of http in all local files that reference INSPIRE schema files, e.g .:

<import namespace = "http://inspire.ec.europa.eu/schemas/base/3.3" schemaLocation = "https://inspire.ec.europa.eu/schemas/base/3.3/BaseTypes.xsd" />

Important: "https" only for the attribute "schemaLocation", not for the "namespace"!

Or download all INSPIRE schema files from the JRC server at https://inspire.ec.europa.eu/schemas/ and adapt them so that all references are resolved locally, e.g.

<import namespace = "http://inspire.ec.europa.eu/schemas/base/3.3" schemaLocation = "../ base / 3.3 / BaseTypes.xsd" />

However, we see the need for deegree to be able to handle this protocol change. We are currently working on a pull request to resolve this issue.

**Closed** 2021-03-12 10:36 UTC
Labels: TMC discussion, blocks release, bug

**Comment by tfr42** [comment] 2021-03-18 13:06
Bugfix version 3.4.16 contains the PR #1131. Download via GitHub and www.deegree.org available soon.

**Comment by tfr42** [comment] 2021-04-11 18:14
Bug fix version ready to download from https://github.com/deegree/deegree3/releases and    https://www.deegree.org/download/.
