### ISSUE TITLE
Rest-Api throws error when upload a new File

### ISSUE THREAD

**Issue by roesgTo** [deegree/deegree3#988] opened 2019-06-19 08:50 UTC
The file upload of configuration files via the REST-API does not work correctly. The Response is HTTP 200 , but there is also this error message: "Unable to upload file: datasources / feature / test-upload.xml". The file is not written to the workspace (as expected with HTTP 200).

I checked the code. Two tests are carried out:
1. workspace-path exists?
2. file-path exists?
If one of the two checks fails, the above error message will appear.

Example:
"http://serverurl/config/upload/datasources/feature/test-upload2.xml" 
Upload in Default-Workspace(workspace-path exists :true)
File "$Workspace/datasources/feature/test-upload2.xml" was not found (file-path exists: false
However, if this file has been previously created in the workspace, it will be successfully overwritten by the upload process (HTTP 200: "test-upload.xml uploaded")

Solution:
The file-path must be checked without the file.

current Check:
does the file "$Workspace/datasources/feature/test-upload2.xml" exist?

new Check:
does the folder "$Workspace/datasources/feature exist?

In addition, it would be very helpfull, if if another HTTP StatusCode will be returned when this error message appears (HTTP 400,404)

**Comment by tfr42** [comment] 2019-06-24 14:06
Thanks for your feedback. Can you please check the deegree version? If the version is 3.4.4 or later the issue you are reporting may be caused by the following PR https://github.com/deegree/deegree3/pull/955.
Please see the documentation how to secure the REST interface http://download.deegree.org/documentation/3.4.7/html/installation.html#securing-deegree.

**Comment by roesgTo** [comment] 2019-06-24 14:52
I was using Version 3.4.7. 
This PR implements the code, that causes the errormessage.
[https://github.com/deegree/deegree3/pull/955/commits/fa34625bebcd077ca03c52c14338cd88d1c517b2](https://github.com/deegree/deegree3/pull/955/commits/fa34625bebcd077ca03c52c14338cd88d1c517b2)

`                if ( !FileUtils.directoryContains( workspaceDir, dest ) ) {
                    IOUtils.write( "Unable to upload file: " + p.second + ".\n", resp.getOutputStream() );
                    return;
                }`

Maybe i am wrong, but i read this code like:
"If the File does not already exist in the Workspace, then throw an error." => Uploading a new File is not possible.

I do not get the connection to the Security of the REST interface. Sure it was a PR to secure the Rest-Interface, but the Problem is not caused by a missing Security-configuration

**Comment by tfr42** [comment] 2019-06-26 08:37
The changes you are referring to were merged into master with PR #955 to resolve #942 and #943. The changes were done on purpose as pointed out in the deegree documentation. 
We will carefully review the changes of PR #955 and discuss the change you propose during the next TMC meeting. 
Of course any kind of contribution is welcome and we highly appreciate if you can open a pull request with the changes you are proposing.

**Comment by tfr42** [comment] 2019-07-05 09:33
@roesgTo We have have discussed your proposal during todays TMC meeting. We will look for a solution asap. Can you post ar `curl` or `wget` commands you are using?

**Comment by roesgTo** [comment] 2019-07-05 10:41
We are using neither Curl nor wget. But this curl may work:
curl -X PUT -i 'http://serverurl/config/upload/datasources/feature/test-upload2.xml' --data '<SQLFeatureStore>...</SQLFeatureStore>'

**Closed** 2019-09-06 10:10 UTC
Labels: bug, console, contributions welcome
